name: snake_game_app
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  lottie: ^3.1.3
  animated_toggle_switch: ^0.8.3
  segmented_button_slide: ^2.0.0
  vibration: ^2.0.1
  audioplayers: ^6.1.0
  fluttertoast: ^8.2.8
  flutter_joystick: ^0.2.1













dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie_images/
    - assets/audio/
    - assets/images/

